# Generated by Django 6.0.5 on 2026-05-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('bahan', models.TextField()),
                ('langkah_pembuatan', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='resep_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
