# Generated by Django 6.0.5 on 2026-05-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_resep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resep',
            old_name='langkah_pembuatan',
            new_name='langkah',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resep',
            name='gambar',
        ),
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_catatan', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_resep.resep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dilihat', models.DateTimeField(auto_now_add=True)),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_resep.resep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
